### ISSUE TITLE
Error on deferring PebbleReadyEvent

### ISSUE THREAD

**Issue by amandahla** [canonical/postgresql-k8s-operator#203]
## Steps to reproduce

1. Deploy the charm 14/stable   73

## Expected behavior
Charm successfully deployed.

## Actual behavior

```
App                       Version  Status   Scale  Charm                     Channel    Rev  Address      Exposed  Message      
synapse-db                14.7     waiting      1  postgresql-k8s            14/stable   73  1.1.1.1   no       installing agent

Unit                         Workload  Agent  Address       Ports  Message
synapse-db/0*                blocked   idle   2.2.2.2         failed to create k8s resources
```

Hypothesis: The Postgresql cluster is taking some time to start so the PebbleReadyEvent is deferred multiple times until the cluster finally starts. The problem is that while running the pebble_ready method responsible for this event multiple times, the k8s resources are created the first time but in the following, the charm is blocked because they already exist

## Versions

Operating system: Ubuntu 20.04.6 LTS

Juju CLI: 2.9.43-ubuntu-amd64

Juju agent: 2.9.42

Charm revision: 14/stable   73

microk8s: 
kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-17T21:57:40Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

## Log output

Juju debug log: 

```
2023-07-17T19:55:38.205Z [container-agent] 2023-07-17 19:55:38 DEBUG juju-log database-peers:10: Re-emitting deferred event <PebbleReadyEvent via PostgresqlOperatorCharm/on/postgresql_pebble_ready[13]>
....
....
2023-07-17T19:55:39.965Z [container-agent] 2023-07-17 19:55:39 ERROR juju-log database-peers:10: failed to create k8s resources
2023-07-17T19:55:39.965Z [container-agent] Traceback (most recent call last):
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     resp.raise_for_status()
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/httpx/_models.py", line 749, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     raise HTTPStatusError(message, request=request, response=self)
2023-07-17T19:55:39.965Z [container-agent] httpx.HTTPStatusError: Client error '409 Conflict' for url 'https://.../api/v1/namespaces/stg-synapse/services'
2023-07-17T19:55:39.965Z [container-agent] For more information check: https://httpstatuses.com/409
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] During handling of the above exception, another exception occurred:
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] Traceback (most recent call last):
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/./src/charm.py", line 521, in _create_resources
2023-07-17T19:55:39.965Z [container-agent]     client.create(resource)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/client.py", line 359, in create
2023-07-17T19:55:39.965Z [container-agent]     return self._client.request("post", name=name, namespace=namespace, obj=obj,
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 245, in request
2023-07-17T19:55:39.965Z [container-agent]     return self.handle_response(method, resp, br)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
2023-07-17T19:55:39.965Z [container-agent]     self.raise_for_status(resp)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     raise transform_exception(e)
2023-07-17T19:55:39.965Z [container-agent] lightkube.core.exceptions.ApiError: services "synapse-db-primary" already exists
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] During handling of the above exception, another exception occurred:
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] Traceback (most recent call last):
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     resp.raise_for_status()
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/httpx/_models.py", line 749, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     raise HTTPStatusError(message, request=request, response=self)
2023-07-17T19:55:39.965Z [container-agent] httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://.../api/v1/namespaces/stg-synapse/services/synapse-db-primary'
2023-07-17T19:55:39.965Z [container-agent] For more information check: https://httpstatuses.com/422
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] During handling of the above exception, another exception occurred:
2023-07-17T19:55:39.965Z [container-agent] 
2023-07-17T19:55:39.965Z [container-agent] Traceback (most recent call last):
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/./src/charm.py", line 450, in _initialize_cluster
2023-07-17T19:55:39.965Z [container-agent]     self._create_resources()
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/./src/charm.py", line 529, in _create_resources
2023-07-17T19:55:39.965Z [container-agent]     client.replace(resource)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/client.py", line 390, in replace
2023-07-17T19:55:39.965Z [container-agent]     return self._client.request("put", name=name, namespace=namespace, obj=obj,
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 245, in request
2023-07-17T19:55:39.965Z [container-agent]     return self.handle_response(method, resp, br)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
2023-07-17T19:55:39.965Z [container-agent]     self.raise_for_status(resp)
2023-07-17T19:55:39.965Z [container-agent]   File "/var/lib/juju/agents/unit-synapse-db-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
2023-07-17T19:55:39.965Z [container-agent]     raise transform_exception(e)
2023-07-17T19:55:39.965Z [container-agent] lightkube.core.exceptions.ApiError: Service "synapse-db-primary" is invalid: metadata.resourceVersion: Invalid value: "": must be specified for an update
2023-07-17T19:55:40.016Z [container-agent] 2023-07-17 19:55:40 DEBUG juju-log database-peers:10: Emitting Juju event database_peers_relation_changed.
```

## Additional context

Discussion about event.defer usage:
https://github.com/canonical/operator/issues/935#issue-1722066396

**Comment by marceloneppel** [comment]
Hi @amandahla!

The issue seems to be the same that was fixed on https://github.com/canonical/postgresql-k8s-operator/releases/tag/rev84.

Can you try with the revision form the `14/beta` channel?

**Comment by amandahla** [comment]
> Hi @amandahla!
> 
> The issue seems to be the same that was fixed on https://github.com/canonical/postgresql-k8s-operator/releases/tag/rev84.
> 
> Can you try with the revision form the `14/beta` channel?

Thanks! Now is not blocked anymore but I found out another issue, I asked for help here on [MM](https://chat.charmhub.io/charmhub/pl/tbzxtd666p8j7yswji56994gye).
