### ISSUE TITLE
Relation with s3-integrator fails on juju 3.1.5

### ISSUE THREAD

**Issue by dragomirp** [canonical/postgresql-k8s-operator#238]
## Expected behavior
Stanza create works successfully.

## Actual behavior
PgBackrest stanza-create fails with `backup and archive info files exist but do not match the database`

## Versions

Operating system: 

Juju CLI: 3.1.5

Juju agent: 3.1.5

Charm revision: 132

microk8s: 

## Log output

Juju debug log: 
```
unit-postgresql-k8s-1: 17:27:39 ERROR unit.postgresql-k8s/1.juju-log s3-parameters:12: non-zero exit code 28 executing ['pgbackrest', '--stanza=postgresql.patroni-postgresql-k8s', 'stanza-create'], stdout='', stderr="WARN: unable to check pg2: [HostConnectError] unable to connect to 'postgresql-k8s-0.postgresql-k8s-endpoints:8432': [111] Connection refused\nERROR: [028]: backup and archive info files exist but do not match the database\n       HINT: is this the correct stanza?\n       HINT: did an error occur during stanza-upgrade?\n"
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 296, in _initialise_stanza
    self._execute_command(["pgbackrest", f"--stanza={self.stanza_name}", "stanza-create"])
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 209, in _execute_command
    ).wait_output()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/pebble.py", line 1355, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 28 executing ['pgbackrest', '--stanza=postgresql.patroni-postgresql-k8s', 'stanza-create'], stdout='', stderr="WARN: unable to check pg2: [HostConnectError] unable to connect to 'postgresql-k8s-0.postgresql-k8s-endpoints:8432': [111] Connection refused\nERROR: [028]: backup and archive info files exist but do not match the database\n       HINT: is this the correct stanza?\n       HINT: did an error occur during stanza-upgrade?\n"
```

**Comment by dragomirp** [comment]
Initial error was likely caused by populated bucket, but subsequently pgbackrest check stanza enters a fail loop:
```
2023-09-07T16:44:36.516Z [postgresql] Exception in thread Thread-371 (process_request_thread):
2023-09-07T16:44:36.516Z [postgresql] Traceback (most recent call last):
2023-09-07T16:44:36.516Z [postgresql]   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2023-09-07T16:44:36.517Z [postgresql]     self.run()
2023-09-07T16:44:36.517Z [postgresql]   File "/usr/lib/python3.10/threading.py", line 953, in run
2023-09-07T16:44:36.517Z [postgresql]     self._target(*self._args, **self._kwargs)
2023-09-07T16:44:36.517Z [postgresql]   File "/usr/lib/python3/dist-packages/patroni/api.py", line 886, in process_request_thread
2023-09-07T16:44:36.517Z [postgresql]     request.do_handshake()
2023-09-07T16:44:36.517Z [postgresql]   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
2023-09-07T16:44:36.517Z [postgresql]     self._sslobj.do_handshake()
2023-09-07T16:44:36.517Z [postgresql] ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1007)
2023-09-07T16:44:36.518Z [pebble] Check "postgresql" failure 234 (threshold 3): Get "http://postgresql-k8s-0.postgresql-k8s-endpoints:8008/health": read tcp 10.1.103.158:58196->10.1.103.158:8008: read: connection reset by peer
```

**Comment by dragomirp** [comment]
Fixed on edge (rev. 136).
