### ISSUE TITLE
An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/postgresql-k8s-operator#256]
Today I ran into an issue where all 3 of my postgresql-k8s units tried to configure backups. This caused some tracebacks in debug-log:

```
unit-postgresql-k8s-1: 13:32:31 ERROR unit.postgresql-k8s/1.juju-log s3-parameters:11: Couldn't create bucket named 'pgsql-demo-3' in region=us-west-2.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 170, in _create_bucket_if_not_exists
    bucket.create(CreateBucketConfiguration={"LocationConstraint": region})
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
unit-postgresql-k8s-2: 13:32:31 ERROR unit.postgresql-k8s/2.juju-log s3-parameters:11: Couldn't create bucket named 'pgsql-demo-3' in region=us-west-2.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/backups.py", line 170, in _create_bucket_if_not_exists
    bucket.create(CreateBucketConfiguration={"LocationConstraint": region})
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
unit-postgresql-k8s-0: 13:32:31 INFO unit.postgresql-k8s/0.juju-log s3-parameters:11: Created bucket 'pgsql-demo-3' in region=us-west-2
```

This has also left two of my units in a blocked state:

```
App                        Version  Status   Scale  Charm                      Channel  Rev  Address         Exposed  Message
app                                 active       1  postgresql-test-app        stable     5  10.152.183.29   no
data-integrator                     waiting      1  data-integrator            edge      13  10.152.183.224  no       installing agent
postgresql-k8s             14.9     waiting      3  postgresql-k8s             14/edge  139  10.152.183.94   no       installing agent
s3-integrator                       active       1  s3-integrator              stable    13  10.152.183.106  no
tls-certificates-operator           active       1  tls-certificates-operator  stable    22  10.152.183.253  no

Unit                          Workload  Agent  Address       Ports  Message
app/0*                        active    idle   10.1.89.156
data-integrator/0*            blocked   idle   10.1.114.32          Please relate the data-integrator with the desired product
postgresql-k8s/0*             active    idle   10.1.89.160          Primary
postgresql-k8s/1              blocked   idle   10.1.114.35          failed to access/create the bucket, check your S3 settings
postgresql-k8s/2              blocked   idle   10.1.248.228         failed to access/create the bucket, check your S3 settings
s3-integrator/0*              active    idle   10.1.114.36
tls-certificates-operator/0*  active    idle   10.1.89.161
```

**Comment by dragomirp** [comment]
Issue should be fixed on edge (rev. 142)
