### ISSUE TITLE
Error after relating to S3 integrator and the Juju leader unit is not the PostgreSQL primary

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-k8s-operator#370]
## Steps to reproduce
1. Deploy 3 units of the PostgreSQL and 1 unit of the S3 integrator charms.
2. Execute `curl -X POST {ip-of-primary-unit}:8008/switchover -d '{"leader": "primary-unit-name-replacing-the-slash-to-hyphen", "candidate": "sync_standby-unit-name-replacing-the-slash-to-hyphen"}'`.
3. Configure the S3 integrator and relate it to PostgreSQL.

## Expected behavior
No error (stanza should be initialised correctly).

## Actual behavior
```
unit-postgresql-k8s-0: 11:52:51 ERROR unit.postgresql-k8s/0.juju-log s3-parameters:62: non-zero exit code 56 executing ['pgbackrest', '--stanza=prod-data-visualization.patroni-postgresql-k8s', 'stanza-create'], stdout='', stderr='ERROR: [056]: unable to find primary cluster - cannot proceed\n       HINT: are all available clusters in recovery?\n'
```

## Versions
Charm revision: 177

## Log output
Juju debug log: 
https://pastebin.canonical.com/p/7xrhhG8n4Z/

## Additional context
[Matrix discussion](https://matrix.to/#/!BukWfnyOTgQSKAxdtT:ubuntu.com/$tBc9pgHKUckyT-gyqGJ3iiutHmvlwPmf-TOz_Aaze1g?via=ubuntu.com&via=matrix.org).

**Comment by marceloneppel** [comment]
Revision 190 (from the 14/stable channel) contains the fix for this issue.

**Comment by Zvirovyi** [comment]
I think issue is came back, @marceloneppel.

## Steps to reproduce
The same steps as is in original issue.


## Expected behavior
Stanza should be initialized correctly.


## Actual behavior
![Знімок екрана з 2024-08-07 13-23-24](https://github.com/user-attachments/assets/5f1b96d9-19db-478e-abba-8778646857c0)
![Знімок екрана з 2024-08-07 13-23-50](https://github.com/user-attachments/assets/b344f35d-0e9d-466d-8087-dc0fdb419242)

## Versions


Operating system: Ubuntu 24.04 LTS


Juju CLI: 3.5.3-genericlinux-amd64


Juju agent: 3.5.3


Charm revision: 349


microk8s: MicroK8s v1.30.1 revision 6843


## Log output


Juju debug log: [k8s_issue_s3_primary_leader_desync.log](https://github.com/user-attachments/files/16522163/k8s_issue_s3_primary_leader_desync.log)

pgBackRest error is different though similar:
```
unit-postgresql-k8s-0: 13:23:44 DEBUG unit.postgresql-k8s/0.juju-log s3-parameters:4: Running command pgbackrest --stanza=dev.patroni-postgresql-k8s stanza-create
unit-postgresql-k8s-0: 13:23:45 ERROR unit.postgresql-k8s/0.juju-log s3-parameters:4: non-zero exit code 28 executing ['pgbackrest', '--stanza=dev.patroni-postgresql-k8s', 'stanza-create'], stdout='', stderr='ERROR: [028]: backup and archive info files exist but do not match the database\n       HINT: is this the correct stanza?\n       HINT: did an error occur during stanza-upgrade?\n'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/backups.py", line 457, in _initialise_stanza
    self._execute_command(["pgbackrest", f"--stanza={self.stanza_name}", "stanza-create"])
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/backups.py", line 291, in _execute_command
    return process.wait_output()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 28 executing ['pgbackrest', '--stanza=dev.patroni-postgresql-k8s', 'stanza-create'], stdout='', stderr='ERROR: [028]: backup and archive info files exist but do not match the database\n       HINT: is this the correct stanza?\n       HINT: did an error occur during stanza-upgrade?\n'
unit-postgresql-k8s-0: 13:23:45 INFO juju.worker.uniter.operation ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
```



## Additional context

I've checked S3 relation code and found the next issue:
In `def _on_s3_credential_changed(self, event: CredentialsChangedEvent)` func, we have check for the primary:
```
# Verify the s3 relation only on the primary.
        if not self.charm.is_primary:
            return
```
But function `def can_use_s3_repository(self) -> Tuple[bool, Optional[str]]`, that should verify is S3 stanza eligible to work with before initializing it, really do the check only if the unit is the leader:
```
        if self.charm.unit.is_leader():
            for stanza in json.loads(stdout):
```
So, when leader / primary is in desync, S3 relation code just not works properly.
