### ISSUE TITLE
any_cpu_to_cores function fails when cpu_str has something after "m"

### ISSUE THREAD

**Issue by lk-1984** [canonical/postgresql-k8s-operator#437]
## Steps to reproduce

Deploy with

`juju deploy postgresql-k8s --channel 14/stable --trust`

into Azure Kubernetes Service.

## Expected behavior

The function would detect that the string passed into int() can be parsed.

## Actual behavior

The any_cpu_to_cores() function fails.

https://github.com/canonical/postgresql-k8s-operator/blob/main/src/utils.py#L70

because the cpu_str has something else than "m" at the end of the cpu_str. Therefore int() fails with

`invalid literal for int() with base 10: '7820m'`.

## Versions

Operating system: Ubuntu 22.04

Juju CLI: 3.4.1-ubuntu-amd64

Juju agent: 

Charm revision: 

microk8s: N/A

## Log output

Juju debug log: 

```
2024-04-03T09:43:16.040Z [container-agent] 2024-04-03 09:43:16 ERROR juju-log certificates:16: Uncaught exception while in charm code:
2024-04-03T09:43:16.040Z [container-agent] Traceback (most recent call last):
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1556, in <module>
2024-04-03T09:43:16.040Z [container-agent]     main(PostgresqlOperatorCharm, use_juju_for_storage=True)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 436, in main
2024-04-03T09:43:16.040Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-04-03T09:43:16.040Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 351, in emit
2024-04-03T09:43:16.040Z [container-agent]     framework._emit(event)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
2024-04-03T09:43:16.040Z [container-agent]     self._reemit(event_path)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
2024-04-03T09:43:16.040Z [container-agent]     custom_handler(event)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 1821, in _on_relation_changed
2024-04-03T09:43:16.040Z [container-agent]     self.on.certificate_available.emit(
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 351, in emit
2024-04-03T09:43:16.040Z [container-agent]     framework._emit(event)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
2024-04-03T09:43:16.040Z [container-agent]     self._reemit(event_path)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
2024-04-03T09:43:16.040Z [container-agent]     custom_handler(event)
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/postgresql_k8s/v0/postgresql_tls.py", line 141, in _on_certificate_available
2024-04-03T09:43:16.040Z [container-agent]     if not self.charm.push_tls_files_to_workload():
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1299, in push_tls_files_to_workload
2024-04-03T09:43:16.040Z [container-agent]     return self.update_config()
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1350, in update_config
2024-04-03T09:43:16.040Z [container-agent]     available_cpu_cores, available_memory = self.get_available_resources()
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1527, in get_available_resources
2024-04-03T09:43:16.040Z [container-agent]     cpu_cores = self.get_node_cpu_cores()
2024-04-03T09:43:16.040Z [container-agent]   File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1523, in get_node_cpu_cores
2024-04-03T09:43:16.040Z [container-agent]     return int(node.status.allocatable["cpu"])
2024-04-03T09:43:16.040Z [container-agent] ValueError: invalid literal for int() with base 10: '7820m'
```

**Comment by lk-1984** [comment]
One possible cause is that somewhere it is expected that "m" is not part of the string that tells allocated CPU amount.

"cpu_str = 7820mm" ==>> cpu_str[:-1] ==>> 7820m

**Comment by dragomirp** [comment]
Hi, @lk-1984, can you try `14/edge`? This should be fixed in [rev 212](https://github.com/canonical/postgresql-k8s-operator/releases/tag/rev212)

**Comment by lk-1984** [comment]
@dragomirp Oh yes! I thought that the 14/stable was latest and therefore I assumed that the main branch would matchi it.

So with 14/edge it works.

<img width="772" alt="Screenshot 2024-04-03 135141" src="https://github.com/canonical/postgresql-k8s-operator/assets/105721994/aa6316b4-4b18-467b-979a-0b92fb67450a">
