### ISSUE TITLE
tls-ca-chain not applied to postgresql backups

### ISSUE THREAD

**Issue by mcfly722** [canonical/postgresql-k8s-operator#479]
## Steps to reproduce

I'm trying to configure S3 backups to local storage.

I have local S3 cluster accessible by url=https://my-s3.mydomain.local, and it uses internal truested company root CA certificate chain.

I integrated s3-integrator with postgresql-k8s, and exported all required S3 chain certs (from browser certificate pannel for this site) to .crt format and converted all this public certs to pem using openssl:
```
openssl x509 -in root0.crt -out root0.pem -outform PEM
openssl x509 -in root1.crt -out root1.pem -outform PEM
openssl x509 -in root2.crt -out root2.pem -outform PEM
openssl x509 -in site.crt -out site.pem -outform PEM
```
then I joined all this resulted text pem files to one, and formed single chain.pem file that looks like:
```
-----BEGIN CERTIFICATE-----
***********************************************************
***********************************************************
***********************************************************
***********************************************************
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
***********************************************************
***********************************************************
***********************************************************
***********************************************************
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
***********************************************************
***********************************************************
***********************************************************
***********************************************************
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
***********************************************************
***********************************************************
***********************************************************
***********************************************************
-----END CERTIFICATE-----
```
then installed and integrated s3-integrator, specified my access key and secret-key:
```
juju deploy s3-integrator --channel=latest/stable --revision=18
juju integrate s3-integrator postgresql-k8s
juju run s3-integrator/leader sync-s3-credentials access-key=<my s3 key> secret-key=<my s3 secret>
```
I'm trying to inject this pem chain using command:
```
juju config s3-integrator \
    endpoint="https://my-s3.mydomain.local" \
    bucket="maas-tst-backup" \
    path="/postgresql-k8s" \
    region="us-east-1" \
    tls-ca-chain="$(base64 -w0 chain.pem)"
```
but without success (CERTIFICATE_VERIFY_FAILED in **postgresql-k8s** logs occurs).

I also checked **/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/certifi/cacert.pem** file in postgresql-k8s container, and I also can't find there my chain certs (only other public internet certs)

Looks like s3-integrator tls-ca-chain parameter integration in postgresql-k8s charm not works.

## Expected behavior
My https://my-s3.mydomain.local S3 internal storage should be trusted for backups.

## Actual behavior
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```

## Versions

Operating system: **Ubuntu 22.04.4 LTS**

Juju CLI: **3.4.2-genericlinux-amd64**

microk8s: **MicroK8s v1.28.7 revision 6532**

Juju status: 
```
juju status

Model            Controller          Cloud/Region        Version  SLA          Timestamp
postgresql-maas  microk8s-localhost  microk8s/localhost  3.4.2    unsupported  15:09:55Z

App              Version  Status  Scale  Charm            Channel        Rev  Address         Exposed  Message
data-integrator           active      3  data-integrator  latest/stable   27  10.152.183.177  no
pgbouncer-k8s    1.21.0   active      3  pgbouncer-k8s    1/stable       103  10.152.183.99   no
postgresql-k8s   14.10    active      3  postgresql-k8s   14/stable      193  10.152.183.207  no
s3-integrator             active      1  s3-integrator    latest/stable   18  10.152.183.133  no

Unit                Workload  Agent  Address       Ports  Message
data-integrator/0*  active    idle   10.1.251.120
data-integrator/1   active    idle   10.1.127.99
data-integrator/2   active    idle   10.1.154.107
pgbouncer-k8s/0*    active    idle   10.1.127.96
pgbouncer-k8s/1     active    idle   10.1.251.121
pgbouncer-k8s/2     active    idle   10.1.154.109
postgresql-k8s/0    active    idle   10.1.127.95
postgresql-k8s/1*   active    idle   10.1.251.116
postgresql-k8s/2    active    idle   10.1.154.103         Primary
s3-integrator/0*    active    idle   10.1.127.100
```
## Log output
Juju debug log: 
```
juju model-config -m postgresql-maas logging-config="unit.postgresql-k8s/0=DEBUG"
juju debug-log --include=postgresql-k8s/0

...
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Sending http request: <AWSPreparedRequest stream_output=False, method=HEAD, url=https://my-s3.mydomain.local/maas-tst-backup, headers={'User-Agent': b'Boto3/1.34.29 md/Botocore#1.34.29 ua/2.0 os/linux#5.15.0-106-generic md/arch#x86_64 lang/python#3.10.12 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.34.29 Resource', 'X-Amz-Date': b'20240520T142745Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=************************/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=6164c584a1e2954bacfe66e9b2ba27e23350d0db92a4960da077cb3380225cc1', 'amz-sdk-invocation-id': b'83d8ee19-0d68-4b0b-89fb-eeacc7161bd7', 'amz-sdk-request': b'attempt=4; max=5'}>
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Certificate path: /var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/certifi/cacert.pem
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Starting new HTTPS connection (4): my-s3.mydomain.local:443
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/httpsession.py", line 491, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://my-s3.mydomain.local/maas-tst-backup [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event needs-retry.s3.HeadBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7fe582d6c460>
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: retry needed, retryable exception caught: SSL validation failed for https://my-s3.mydomain.local/maas-tst-backup [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/httpsession.py", line 491, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://my-s3.mydomain.local/maas-tst-backup [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Retry needed, action of: 0.6146639292721581
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event needs-retry.s3.HeadBucket: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x7fe582d6c520>>
unit-postgresql-k8s-1: 14:27:45 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Response received to retry, sleeping for 0.6146639292721581 seconds
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event request-created.s3.HeadBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fe5832f9f00>>
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event choose-signer.s3.HeadBucket: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7fe58381b3d0>>
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event choose-signer.s3.HeadBucket: calling handler <function set_operation_specific_signer at 0x7fe583b3c820>
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event before-sign.s3.HeadBucket: calling handler <function remove_arn_from_signing_path at 0x7fe583b3e9e0>
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Event before-sign.s3.HeadBucket: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <botocore.utils.S3ExpressIdentityResolver object at 0x7fe582d6c580>>
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: Calculating signature using v4 auth.
unit-postgresql-k8s-1: 14:27:46 DEBUG unit.postgresql-k8s/1.juju-log s3-parameters:9: CanonicalRequest:
HEAD
/maas-tst-backup

host:my-s3.mydomain.local
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20240520T142746Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

```

I also see in debug-log of s3-integrator that it correctly loaded my certs in **Updated S3 connection info** message (last string in log) and splitted them to serialized json array:
```
juju model-config -m postgresql-maas logging-config="unit.s3-integrator/0=DEBUG"
juju debug-log --include=integrator/0

unit-s3-integrator-0: 15:11:24 DEBUG unit.s3-integrator/0.juju-log s3-integrator-peers:10: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:24 DEBUG unit.s3-integrator/0.juju-log s3-integrator-peers:10: Emitting Juju event s3_integrator_peers_relation_changed.
unit-s3-integrator-0: 15:11:24 INFO unit.s3-integrator/0.juju-log s3-integrator-peers:10: Missing options: []
unit-s3-integrator-0: 15:11:32 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:32 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_created.
unit-s3-integrator-0: 15:11:33 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:33 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_joined.
unit-s3-integrator-0: 15:11:33 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:33 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_changed.
unit-s3-integrator-0: 15:11:34 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:34 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_joined.
unit-s3-integrator-0: 15:11:35 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:11:35 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_changed.
unit-s3-integrator-0: 15:12:30 DEBUG unit.s3-integrator/0.juju-log ops 2.11.0 up and running.
unit-s3-integrator-0: 15:12:30 DEBUG unit.s3-integrator/0.juju-log Emitting Juju event sync_s3_credentials_action.
unit-s3-integrator-0: 15:12:31 DEBUG unit.s3-integrator/0.juju-log Updated S3 connection info: {'access-key': '************************'}
unit-s3-integrator-0: 15:12:31 DEBUG unit.s3-integrator/0.juju-log Updated S3 connection info: {'secret-key': '*******************************************'}
unit-s3-integrator-0: 15:13:54 DEBUG unit.s3-integrator/0.juju-log ops 2.11.0 up and running.
unit-s3-integrator-0: 15:13:54 DEBUG unit.s3-integrator/0.juju-log Emitting Juju event update_status.
unit-s3-integrator-0: 15:14:23 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:14:23 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_joined.
unit-s3-integrator-0: 15:14:24 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:14:24 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_changed.
unit-s3-integrator-0: 15:14:30 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: ops 2.11.0 up and running.
unit-s3-integrator-0: 15:14:30 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting Juju event s3_credentials_relation_changed.
unit-s3-integrator-0: 15:14:31 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Emitting custom event <CredentialRequestedEvent via S3IntegratorCharm/S3Provider[s3-credentials]/on/credentials_requested[92]>.
unit-s3-integrator-0: 15:14:31 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Desired bucket name: maas-tst-backup
unit-s3-integrator-0: 15:14:31 DEBUG unit.s3-integrator/0.juju-log s3-credentials:11: Updated S3 connection info:
{'access-key': '*************************',
'secret-key': '*******************',
'region': 'us-east-1',
'bucket': 'maas-tst-backup',
'endpoint': 'https://my-s3.mydomain.local',
'path': '/postgresql-k8s',
'tls-ca-chain': '[
"-----BEGIN CERTIFICATE-----\\nMIIFWzC*******************==\\n-----END CERTIFICATE-----",
"-----BEGIN CERTIFICATE-----\\nMIIGRzC*********************************YpWr\\n-----END CERTIFICATE-----",
"-----BEGIN CERTIFICATE-----\\nMIIH8zCCB************************IPE=\\n-----END CERTIFICATE-----"]'}
```

**Comment by mcfly722** [comment]
I also noticed, that command
```
juju run s3-integrator/leader get-s3-connection-info

Running operation 41 with 1 task
  - task 42 on unit-s3-integrator-0

Waiting for task 42...
access-key: '************'
bucket: maas-tst-backup
endpoint: https://my-s3.mydomain.local
path: /postgresql-k8s
region: us-east-1
secret-key: '************'
tls-ca-chain: '[
"-----BEGIN CERTIFICATE-----\nMIIFWzC.............EKCUw==\n-----END CERTIFICATE-----",
"-----BEGIN CERTIFICATE-----\nMIIGRzCCBC+g.......73irYpWr\n-----END CERTIFICATE-----",
"-----BEGIN CERTIFICATE-----\nMIIH8zCCB........vicjEXIPE=\n-----END CERTIFICATE-----"]'
```
returns tls-ca-chain not as json [] array, but as string, that contains this certificates array (don't know is it correct, but looks really strange, like type casting code mistake).

**Comment by mcfly722** [comment]
I also tried to put my certs chain to container to file **/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/certifi/cacert.pem** directly.
it is resolves problem with connection (connection to my S3 establishes), but next error occurs in **postgresql-k8s** logs:
```
Backup failed: Unit cannot perform backups as TLS is not enabled
```

**Comment by dragomirp** [comment]
Hi, @mcfly722, I don't think we are handling the CA chain at the moment. If there's no TLS enable for Postgresql, the backup should be run against the primary unit.

**Comment by mcfly722** [comment]
Im'm enabled TLS and injected by CA chain, but on creating backup next error occurs with Stanza:

```
juju run postgresql-k8s/leader create-backup

Running operation 16 with 1 task
  - task 17 on unit-postgresql-k8s-0

Waiting for task 17...
Action id 17 failed: Stanza was not initialised
```
On list current backups occurs next exception:
```
unit-postgresql-k8s-0: 14:34:07 ERROR unit.postgresql-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/./src/charm.py", line 1556, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/backups.py", line 541, in _on_list_backups_action
    formatted_list = self._generate_backup_list_output()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/backups.py", line 249, in _generate_backup_list_output
    backups = json.loads(output)[0]["backup"]
IndexError: list index out of range
```

**Comment by marceloneppel** [comment]
Hi, @mcfly722! Revision 270 from the `14/edge` channel contains the fix to use the TLS CA chain informed in the S3 integrator.
