### ISSUE TITLE
The inconvenient max_connections formula as a stop factor for HA production configurations

### ISSUE THREAD

**Issue by mcfly722** [canonical/postgresql-k8s-operator#499]
Hello,
We have a HA **postgresql-k8s + pgbouncer-k8s** configuration with three nodes for **MaaS** service, and we faced the 
**FATAL sorry, too many clients already**
postgresql problem.

MaaS service requires at least ~40+10 simultaneously opened connections per controller (we have 3 MaaS controllers), and these empty sessions do not consume any additional CPU time (it just optimizes tcp connection establishment time).

So:
(3 MaaS controllers)  * (~50 sessions per controller) ~=150 sessions.

MaaS connects to pgbouncer-k8s, so each pgbouncer-k8s should have at least 150 sessions to postgresql-k8s.
If you have 3 pgbouncer-k8s pods in HA configuration, it means that postgresql-k8s should be able to accept 150*3~=450 simultaneous connections.

Postgresql has a configuration parameter **max_connections** that you hardcoded with formula: [max_connections=max(4 * os.cpu_count(), 100) ](https://canonical.com/data/docs/postgresql/k8s/r-profiles)

So, according to it, to overcome the 100 session limit for our (3 pgbouncers) configuration, we should have kubernetes nodes with at least 114 CPUs. It is absolutely not justified for empty TCP sessions.

Using [pgbouncer-k8s **pool_mode=transaction/statement**](https://charmhub.io/pgbouncer-k8s/configuration) with **max_db_connections**=33 partially solves this pressure, but with this settings we also see "FATAL sorry, too many clients already" on pgbouncers even for 2 MaaS controllers.

Also, we think that this dependence on nodes CPU's also incorrect because nodes could be pressured by other pods.

We ask you very badly to add **max_connections** as a configurable parameter for postgresql-k8s charm without any additional formulas, because no one will overpay for empty sessions in 15-20 times.

For our production, this functionality is absolutely required. Otherwise, this stop factor will force us to search for another K8S postgresql operator solution where there are no such hardcoded limitations.

## Versions

Operating system: **Ubuntu 22.04.4 LTS**

Juju CLI: **3.4.3-genericlinux-amd64**

Juju agent: **3.4.2**

Charm revision: **postgresql-k8s   14.10 (14/stable rev=193)**

microk8s: **MicroK8s v1.28.10 revision 6829**

#### PGBouncer:
```
microk8s.kubectl exec -it pgbouncer-k8s-0 -n postgresql-maas -c pgbouncer -- cat /var/log/pgbouncer/instance_0/pgbouncer.log

2024-06-06 14:37:24.503 UTC [4619] WARNING server login failed: FATAL sorry, too many clients already
2024-06-06 14:37:24.503 UTC [4619] LOG S-0x564386cabbb0: maasdb/pgbouncer_auth_relation_id_7@10.152.183.145:5432 closing because: login failed (age=0s)
2024-06-06 14:37:35.185 UTC [4619] LOG stats: 0 xacts/s, 0 queries/s, 0 client parses/s, 0 server parses/s, 0 binds/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2024-06-06 14:37:39.516 UTC [4619] LOG S-0x564386cabbb0: maasdb/pgbouncer_auth_relation_id_7@10.152.183.145:5432 new connection to server (from 10.1.51.219:54638)
2024-06-06 14:37:39.520 UTC [4619] WARNING server login failed: FATAL sorry, too many clients already
2024-06-06 14:37:39.520 UTC [4619] LOG S-0x564386cabbb0: maasdb/pgbouncer_auth_relation_id_7@10.152.183.145:5432 closing because: login failed (age=0s)
2024-06-06 14:37:54.516 UTC [4619] LOG S-0x564386cabbb0: maasdb/pgbouncer_auth_relation_id_7@10.152.183.145:5432 new connection to server (from 10.1.51.219:51818)
2024-06-06 14:37:54.519 UTC [4619] WARNING server login failed: FATAL sorry, too many clients already
2024-06-06 14:37:54.519 UTC [4619] LOG S-0x564386cabbb0: maasdb/pgbouncer_auth_relation_id_7@10.152.183.145:5432 closing because: login failed (age=0s)
```
#### Postgresql
```
juju config pgbouncer-k8s max_db_connections=50

microk8s.kubectl exec -it postgresql-k8s-0 -n postgresql-maas -c postgresql -- cat /var/log/postgresql/postgresql-5_1032.log


2024-06-07 10:32:02 UTC [66057]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:02 UTC [66058]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:02 UTC [66059]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:02 UTC [66060]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:02 UTC [66061]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:14 UTC [66072]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.51.219,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:14 UTC [66073]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:14 UTC [66075]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.51.219,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:15 UTC [66076]: user=replication,db=[unknown],app=[unknown],client=10.1.126.241,line=1 FATAL:  no pg_hba.conf entry for replication connection from host "10.1.126.241", user "replication", no encryption
2024-06-07 10:32:17 UTC [66079]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:17 UTC [66080]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:17 UTC [66081]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:17 UTC [66082]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:18 UTC [66083]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:30 UTC [66094]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.51.219,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:30 UTC [66096]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:32 UTC [66097]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:32 UTC [66098]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:33 UTC [66099]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:33 UTC [66100]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:33 UTC [66101]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:47 UTC [66120]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:47 UTC [66121]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:48 UTC [66122]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:48 UTC [66123]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.126.242,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections
2024-06-07 10:32:48 UTC [66124]: user=relation_id_6,db=maasdb,app=[unknown],client=10.1.160.44,line=1 FATAL:  remaining connection slots are reserved for non-replication superuser connections



```

#### MaaS

```
cat /var/snap/maas/common/log/regiond.log


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/utils/__init__.py", line 177, in call_with_lock
    return func(*args, **kwargs)
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/utils/orm.py", line 771, in call_within_transaction
    return func_outside_txn(*args, **kwargs)
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/utils/orm.py", line 574, in retrier
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/security.py", line 54, in _get_shared_secret
    manager = SecretManager()
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/secrets.py", line 79, in __init__
    self._vault_client = get_region_vault_client_if_enabled()
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/vault.py", line 168, in get_region_vault_client_if_enabled
    if Config.objects.get_config("vault_enabled", False):
  File "/snap/maas/35704/lib/python3.10/site-packages/maasserver/models/config.py", line 199, in get_config
    return self.get(name=name).value
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: transaction blocks not allowed in statement pooling mode
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/maas/35704/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server login has been failing, try again later (server_login_retry)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

PostgreSQL sessions limit:
```
SELECT count(*) FROM pg_stat_activity;
101
```
```
show max_connections;
100
```

## Additionl settings:
```
microk8s.kubectl exec -it postgresql-k8s-0 -n postgresql-maas -c postgresql -- cat /var/lib/postgresql/data/pgdata/postgresql.conf

# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

DateStyle = 'ISO, MDY'
TimeZone = 'UTC'
archive_command = '/bin/true'
archive_mode = 'True'
autovacuum = 'True'
autovacuum_analyze_scale_factor = '0.1'
autovacuum_analyze_threshold = '50'
autovacuum_freeze_max_age = '200000000'
autovacuum_vacuum_cost_delay = '2'
autovacuum_vacuum_scale_factor = '0.2'
bytea_output = 'hex'
cluster_name = 'patroni-postgresql-k8s'
constraint_exclusion = 'partition'
default_statistics_target = '100'
default_text_search_config = 'pg_catalog.simple'
effective_cache_size = '24897MB'
from_collapse_limit = '8'
fsync = 'True'
full_page_writes = 'True'
hot_standby = 'on'
join_collapse_limit = '8'
lc_messages = 'en_US.UTF8'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
listen_addresses = '0.0.0.0'
log_autovacuum_min_duration = '60000'
log_checkpoints = 'on'
log_connections = 'False'
log_destination = 'stderr'
log_directory = '/var/log/postgresql'
log_disconnections = 'False'
log_file_mode = '0600'
log_filename = 'postgresql-%w_%H%M.log'
log_hostname = 'off'
log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h,line=%l '
log_lock_waits = 'False'
log_min_duration_sample = '-1'
log_min_duration_statement = '-1'
log_recovery_conflict_waits = 'on'
log_replication_commands = 'on'
log_rotation_age = '1'
log_rotation_size = '0'
log_statement = 'ddl'
log_statement_sample_rate = '1'
log_statement_stats = 'off'
log_temp_files = '1'
log_timezone = 'UTC'
log_truncate_on_rotation = 'on'
logging_collector = 'on'
maintenance_work_mem = '65536'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
password_encryption = 'scram-sha-256'
port = '5432'
shared_buffers = '200'
standard_conforming_strings = 'True'
synchronous_commit = 'True'
synchronous_standby_names = '"postgresql-k8s-2"'
temp_buffers = '1024'
track_commit_timestamp = 'off'
vacuum_freeze_table_age = '150000000'
wal_keep_size = '128MB'
wal_level = 'logical'
wal_log_hints = 'on'
work_mem = '4096'
hba_file = '/var/lib/postgresql/data/pgdata/pg_hba.conf'
ident_file = '/var/lib/postgresql/data/pgdata/pg_ident.conf'
```

```
microk8s.kubectl exec -it pgbouncer-k8s-0 -n postgresql-maas -c pgbouncer -- cat /var/lib/pgbouncer/instance_0/pgbouncer.ini

maasdb = host=postgresql-k8s-primary.postgresql-maas.svc.cluster.local dbname=maasdb port=5432 auth_user=pgbouncer_auth_relation_id_7

maasdb_readonly = host=postgresql-k8s-replicas.postgresql-maas.svc.cluster.local dbname=maasdb port=5432 auth_user=pgbouncer_auth_relation_id_7


[pgbouncer]
listen_addr = *
listen_port = 6432
logfile = /var/log/pgbouncer/instance_0/pgbouncer.log
pidfile = /var/lib/pgbouncer/instance_0/pgbouncer.pid
stats_users = pgbouncer_stats_pgbouncer_k8s
auth_type = md5
user = postgres
max_client_conn = 10000
ignore_startup_parameters = extra_float_digits,options
server_tls_sslmode = prefer
so_reuseport = 1
unix_socket_dir = /var/lib/pgbouncer/instance_0
pool_mode = statement
max_db_connections = 30
default_pool_size = 1
min_pool_size = 1
reserve_pool_size = 1
auth_query = SELECT username, password FROM pgbouncer_auth_relation_id_7.get_auth($1)
auth_file = /var/lib/pgbouncer/userlist.txt
```

**Comment by dragomirp** [comment]
Hi, @mcfly722, we've recently added `experimental_max_connections` configuration to the VM charm, to be able to override the max connection calculation. I will port to the K8s charm and update this ticket.

**Comment by taurus-forever** [comment]
Dear @mcfly722 , thank you for the report!

The [experimental_max_connections](https://charmhub.io/postgresql/configuration?channel=14/candidate#experimental_max_connections) option is already avaiable for VM charm in `14/candidate`.
We are currently adding it for PostgreSQL K8s charm as well, stay tuned.

CC: @delgod , @7annaba3l

**Comment by dragomirp** [comment]
Latest `14/edge` (rev. 274) should have the configuration.

**Comment by marceloneppel** [comment]
The latest `14/stable` (rev. 281 for AMD64 and rev. 280 for ARM64) has this configuration.
