### ISSUE TITLE
Connection rejection rule in `pg_hba.conf`

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-k8s-operator#747]
## Steps to reproduce

1. Run backups periodically, every 2 hours.

## Expected behavior
No connection rejection rule:
```sh
root@postgresql-k8s-0:/# cat /var/lib/postgresql/data/pgdata/pg_hba.conf
Do not edit this file manually!
# It will be overwritten by Patroni!
local all backup peer map=operator
local all monitoring password
hostssl all all 0.0.0.0/0 md5
hostssl replication replication 127.0.0.1/32 md5
hostssl replication replication 127.0.0.6/32 md5
hostssl replication replication postgresql-k8s-0.postgresql-k8s-endpoints.prod-temporal.svc.cluster.local md5
hostssl replication replication postgresql-k8s-1.postgresql-k8s-endpoints.prod-temporal.svc.cluster.local md5
hostssl replication replication postgresql-k8s-2.postgresql-k8s-endpoints.prod-temporal.svc.cluster.local md5
EOF
```

## Actual behavior

Connection rejection rule:
```sh
root@postgresql-k8s-0:/# cat /var/lib/postgresql/data/pgdata/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all backup peer map=operator
local all monitoring password
hostssl all all 0.0.0.0/0 reject
hostssl all all postgresql-k8s-0.postgresql-k8s-endpoints.stg-data-visualization-34.svc.cluster.local md5
hostssl replication replication 127.0.0.1/32 md5
hostssl replication replication 127.0.0.6/32 md5
hostssl replication replication postgresql-k8s-0.postgresql-k8s-endpoints.stg-data-visualization-34.svc.cluster.local md5
hostssl replication replication postgresql-k8s-1.postgresql-k8s-endpoints.stg-data-visualization-34.svc.cluster.local md5
hostssl replication replication postgresql-k8s-2.postgresql-k8s-endpoints.stg-data-visualization-34.svc.cluster.local md5
```

## Versions

Juju agent: 3.4.5

Charm revision: 281

Environment: PS6

## Log output

Juju debug log: 

```sh
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 1384, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 335, in connection
    return self._connection.get()
  File "/usr/lib/python3/dist-packages/patroni/postgresql/connection.py", line 29, in get
    self._connection = psycopg.connect(**self._conn_kwargs)
  File "/usr/lib/python3/dist-packages/patroni/psycopg.py", line 103, in connect
    ret = _connect(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
    Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "127.0.0.1", user "operator", database "postgres", SSL encryption
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "operator", database "postgres", no encryption


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 1265, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 1197, in query
    return self.server.query(sql, *params)
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 1390, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: connection problems
```

## Additional context

MM discussions:
* https://chat.canonical.com/canonical/pl/6ijzw7rzebfz7n7cesh8dkyfho
* https://chat.canonical.com/canonical/pl/17gyxfsas7bhjq8ewh8jnzxbty
* https://chat.canonical.com/canonical/pl/ghswfoygt3bn3q918sxxcmoaty
* https://chat.canonical.com/canonical/pl/buc871tk7jrmtkecjaxdo4smwc
* https://chat.canonical.com/canonical/pl/rr4r7zwehtdctbw6ywuk6c5dzy

**Comment by marceloneppel** [comment]
Connection is disabled at: https://github.com/canonical/postgresql-k8s-operator/blob/2a53fa3efa42b032362ae78d42a4020f4c2b8c24/src/backups.py#L743

Connection should have been enabled again at: https://github.com/canonical/postgresql-k8s-operator/blob/2a53fa3efa42b032362ae78d42a4020f4c2b8c24/src/backups.py#L822
